# Generated by Django 5.2.1 on 2025-06-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_equipo_nombre_est'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='nombre_est',
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
