# Generated by Django 5.2.1 on 2025-06-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_equipo_nombre_est_equipo_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivomovil',
            options={'verbose_name': 'Dispositivo Móvil', 'verbose_name_plural': 'Dispositivos Móviles'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AlterModelOptions(
            name='razonsocial',
            options={'verbose_name': 'Razón Social', 'verbose_name_plural': 'Razones Sociales'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='tipoequipo',
            options={'verbose_name': 'Tipo de Equipo', 'verbose_name_plural': 'Tipos de Equipo'},
        ),
        migrations.AlterField(
            model_name='equipo',
            name='capacidad_almacenamiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad de almacenamiento (GB)'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ram',
            field=models.IntegerField(blank=True, null=True, verbose_name='Memoria RAM (GB)'),
        ),
    ]
