# Generated by Django 5.2.1 on 2025-06-04 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dispositivomovil_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento'),
        ),
    ]
