# Generated by Django 5.2.1 on 2025-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_departamento_remove_empleado_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='razonsocial',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='razonsocial',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='razonsocial',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='razonsocial',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
