# Generated by Django 5.2.1 on 2025-06-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_razonsocial_correo_razonsocial_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fk_razon_social',
        ),
    ]
