# Generated by Django 5.2.1 on 2025-06-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_equipo_fk_razon_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='fk_razon_social',
        ),
        migrations.AddField(
            model_name='equipo',
            name='fk_razon_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.razonsocial'),
        ),
    ]
