# Generated by Django 5.2.2 on 2025-06-05 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_prestamo_fk_razon_social_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_sucursal', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Sucursal',
                'verbose_name_plural': 'Tipos de Sucursal',
            },
        ),
        migrations.AddField(
            model_name='sucursal',
            name='fk_tipo_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipo_sucursal'),
        ),
    ]
