# Generated by Django 5.2.2 on 2025-06-06 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tipo_sucursal_sucursal_fk_tipo_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_de_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='fk_razon_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.razonsocial'),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fk_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empleado')),
                ('fk_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipo')),
            ],
            options={
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
    ]
