# Generated by Django 5.2.2 on 2025-06-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tipomantenimiento_mantenimiento_tipo_mantenimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivomovil',
            name='marca',
        ),
        migrations.AddField(
            model_name='equipo',
            name='licencia_office',
            field=models.BooleanField(default=False, verbose_name='Licencia Office'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='version_windows',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión de Windows'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fk_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fk_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='dispositivomovil',
            name='fk_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fk_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fk_sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fk_razon_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.razonsocial', verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fk_sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='diagnostico',
            field=models.CharField(max_length=255, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estatus',
            field=models.CharField(default='Pendiente', max_length=50, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fk_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='solucion',
            field=models.CharField(max_length=255, verbose_name='Solución'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tecnico',
            field=models.CharField(max_length=100, verbose_name='Técnico'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipomantenimiento', verbose_name='Tipo de Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='fk_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fk_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fk_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='fk_razon_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.razonsocial', verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='fk_tipo_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipo_sucursal', verbose_name='Tipo de Sucursal'),
        ),
    ]
