# Generated by Django 5.2.2 on 2025-06-09 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_dispositivomovil_marca_equipo_licencia_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_de_adquisicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_de_alta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Alta'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='fk_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.municipio', verbose_name='Municipio'),
        ),
    ]
