# Generated by Django 5.2.2 on 2025-06-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_equipo_fecha_de_adquisicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivomovil',
            name='modelo',
        ),
    ]
