# Generated by Django 5.2.2 on 2025-06-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_dispositivomovil_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tipo_almacenamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipoalmacenamiento'),
        ),
    ]
