# Generated by Django 5.2.1 on 2025-06-12 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_equipo_tipo_almacenamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fk_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.equipo', verbose_name='Equipo'),
        ),
    ]
