# Generated by Django 5.2.1 on 2025-06-13 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_asignacion_fk_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fk_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.equipo', verbose_name='Equipo'),
        ),
    ]
