# Generated by Django 5.2.2 on 2025-07-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_prestamo_fk_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC del Proveedor'),
        ),
    ]
