# Generated by Django 5.2.2 on 2025-08-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_equipo_folio_equipo_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='nuevo',
            field=models.BooleanField(default=False, verbose_name='nuevo'),
        ),
    ]
