# Generated by Django 5.2.2 on 2025-07-23 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_equipo_folio_equipo_rfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoEliminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_id_original', models.IntegerField(verbose_name='ID Original del Equipo')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('fecha_de_adquisicion', models.DateField(blank=True, null=True)),
                ('fecha_de_alta', models.DateField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad_almacenamiento', models.IntegerField(blank=True, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('procesador', models.CharField(blank=True, max_length=100, null=True)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('tipo_equipo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('sucursal_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('razon_social_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_almacenamiento_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('disponibilidad_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_eliminacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Eliminación')),
                ('usuario_eliminacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario que Eliminó')),
                ('motivo_eliminacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Eliminación')),
                ('datos_completos', models.JSONField(blank=True, null=True, verbose_name='Datos Completos del Equipo')),
            ],
            options={
                'verbose_name': 'Equipo Eliminado',
                'verbose_name_plural': 'Equipos Eliminados',
                'ordering': ['-fecha_eliminacion'],
            },
        ),
    ]
