# Generated by Django 5.2.2 on 2025-07-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_equipoeliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoeliminado',
            name='disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.disponibilidad', verbose_name='Disponibilidad'),
        ),
        migrations.AddField(
            model_name='equipoeliminado',
            name='razon_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.razonsocial', verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='equipoeliminado',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='equipoeliminado',
            name='tipo_almacenamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipoalmacenamiento', verbose_name='Tipo de Almacenamiento'),
        ),
        migrations.AddField(
            model_name='equipoeliminado',
            name='tipo_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipoequipo', verbose_name='Tipo de Equipo'),
        ),
        migrations.AlterField(
            model_name='equipoeliminado',
            name='disponibilidad_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipoeliminado',
            name='tipo_almacenamiento_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipoeliminado',
            name='tipo_equipo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
