# Generated by Django 5.2.2 on 2025-08-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_equipo_nuevo'),
    ]

    operations = [
        migrations.CreateModel(
            name='conexiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conexion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Conexion',
                'verbose_name_plural': 'Tipos de Conexion',
            },
        ),
        migrations.CreateModel(
            name='isp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_isp', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedor',
            },
        ),
        migrations.AddField(
            model_name='sucursal',
            name='cuenta',
            field=models.CharField(max_length=50, null=True, verbose_name='Cuenta'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='Contrasena'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='conexion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.conexiones', verbose_name='Tipo de Conexion'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='nombre_isp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.isp', verbose_name='Proveedor'),
        ),
    ]
