# Generated by Django 5.2.2 on 2025-06-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aires',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='operativo', max_length=30)),
                ('ultima_revision', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Aire',
                'verbose_name_plural': 'Aires',
            },
        ),
    ]
